import { useState } from 'react';
import './Explore.css';
import { IoIosArrowDown } from 'react-icons/io';
import BloodTable from '../../utilcomponents/HomeComponents/learnoAboutDonotion/BloodTable/BloodTable';

export default function Explore() {
  const [ExploreSectionContentActive, setExploreSectionContentActive] =
    useState(0);

  return (
    <div className="Explore">
      <div className="Explore-landing-section">
        <img
          src="./images/Explore-Anime.webp"
          alt="Explore-Image"
          className="Explore-landing-section-image"
        />
        <div className="Explore-landing-section-overlay">
          <p className="Explore-landing-section-heading">EXPLORE</p>
        </div>
      </div>

      <div className="explore-section-content-section-container">
        {/* 
          QUESTION 1 
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 1
                ? setExploreSectionContentActive(1)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              What is BLOOD?
            </p>
            <div
              className={
                ExploreSectionContentActive === 1
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 1
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            Blood donation is an important and altruistic gesture that can save
            a patient's life. Donors help to maintain a consistent and healthy
            blood supply, which is necessary for a variety of medical operations
            such as surgeries, cancer and chronic illness treatments, and
            emergency care. Individuals who donate blood play an important role
            in saving lives and supporting the health and well-being of those in
            their communities.
          </div>
        </div>

        {/* 
          QUESTION 1 
          ENDS 
          HERE */}

        {/* 
          QUESTION 2 
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 2
                ? setExploreSectionContentActive(2)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              Use of the Blood
            </p>
            <div
              className={
                ExploreSectionContentActive === 2
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 2
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            The primary use of blood is to sustain life by providing essential
            functions within the body. These functions include:
            <ul>
              <li>
                <b>Oxygen Transport:</b> Blood carries oxygen from the lungs to
                cells throughout the body, ensuring their proper function and
                metabolism.
              </li>
              <li>
                <b>Nutrient Delivery:</b> Blood transports nutrients absorbed
                from the digestive system to cells, providing energy and
                essential building blocks for growth and repair.
              </li>
              <li>
                <b>Waste Removal:</b> Blood carries metabolic waste products,
                such as carbon dioxide and urea, away from cells to be
                eliminated from the body through the lungs, kidneys, and other
                organs.
              </li>
              <li>
                <b>Immune Defense:</b> Blood contains white blood cells and
                antibodies that defend against pathogens, viruses, and bacteria,
                helping the body fight infections and diseases.
              </li>
              <li>
                <b>Temperature Regulation:</b> : Blood helps regulate body
                temperature by redistributing heat generated by metabolism and
                adjusting blood flow near the body's surface in response to
                environmental conditions.
              </li>
              <li>
                <b>Clotting:</b> Blood contains platelets and clotting factors
                that form clots to stop bleeding and prevent excessive blood
                loss after injury.
              </li>
            </ul>
          </div>
        </div>

        {/* 
          QUESTION 2 
          ENDS 
          HERE */}

        {/* 
          QUESTION 3
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 3
                ? setExploreSectionContentActive(3)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              Donors with compatible blood groupings
            </p>
            <div
              className={
                ExploreSectionContentActive === 3
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 3
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            <div>
              <b>Advantages:</b>
            </div>
            <div>
              <b>Blood Type O (Universal Donor):</b>
            </div>
            <div>
              <b>Advantages:</b>
              Can donate to individuals with any blood type (A, B, AB, or O),
              making it invaluable in emergency situations when the recipient's
              blood type is unknown.
            </div>
            <div>
              <b>Advantages:</b>
              Blood type O negative is considered the "universal donor" for red
              blood cells, plasma, and platelets, as it lacks A, B, and Rh
              antigens, reducing the risk of transfusion reactions
            </div>
            <div>
              <b>Blood Type AB (Universal Recipient):</b>
            </div>
            <div>
              <b>Advantages:</b>
              Can receive blood from individuals with any blood type (A, B, AB,
              or O), making it versatile and reducing the need for specific
              blood type matches in transfusions.
            </div>
            <div>
              <b>Advantages:</b>
              Individuals with blood type AB positive are often in demand for
              platelet and plasma donations, as their blood type is compatible
              with many recipients.
            </div>
            <div>
              <b>Rh-Negative Blood Types:</b>
            </div>
            <div>
              <b>Advantages:</b>
              Rh-negative individuals can donate blood to both Rh-positive and
              Rh-negative recipients, increasing the pool of potential donors.
            </div>
            <div>
              <b>Advantages:</b>
              Rh-negative blood is often used in cases where the recipient's Rh
              status is unknown or when Rh compatibility is required but not
              readily available.
            </div>
            <div style={{ 'margin-top': '1rem' }}></div>
            <div>
              <b>Disadvantages:</b>
            </div>
            <div>
              <b>Blood Type O (Universal Donor):</b>
            </div>
            <div>
              <b>Disadvantage:</b>
              Individuals with blood type O can only receive blood from other
              type O donors, limiting their options in case of blood
              transfusions.
            </div>
            <div>
              <b>Blood Type AB (Universal Recipient):</b>
              <div>
                <b>Disdvantage:</b>
                Blood type AB individuals can only donate to other AB
                recipients, reducing the availability of compatible donors.
              </div>
              <div>
                <b>Disadvantages:</b>
                Individuals with blood type AB may be at a higher risk of
                sensitization to foreign antigens due to exposure to a wide
                range of blood types.
              </div>

              <div>
                <b>Rh-Negative Blood Types:</b>
                Rh-negative individuals can only receive Rh-negative blood,
                which may be less readily available compared to Rh-positive
                blood. Rh-negative blood is relatively rare compared to
                Rh-positive blood, which can pose challenges in emergency
                situations or when specific Rh-negative blood types are
                required.
              </div>
            </div>
            <div style={{ 'margin-top': '3rem' }}>
              <BloodTable />
            </div>
          </div>
        </div>

        {/* 
          QUESTION 3
          ENDS 
          HERE */}

        {/* 
          QUESTION 4 
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 4
                ? setExploreSectionContentActive(4)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              Who can donate?
            </p>
            <div
              className={
                ExploreSectionContentActive === 4
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 4
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            <ul>
              <li>
                <b>Age:</b> Typically 17 years old or older (16 with parental
                consent).
              </li>
              <li>
                <b>Weight: </b> Generally meeting minimum weight requirements,
                usually around 50 kgs.
              </li>
              <li>
                <b>Height:</b> Not typically a specific requirement.
              </li>
              <li>
                <b>Health:</b> Recent travel to certain regions may affect
                eligibility.
              </li>
              <li>
                <b>Travel History:</b> Recent travel to certain regions may
                effect eligibility.
              </li>
              <li>
                <b>Medication:</b> Some Medication may disqualify donors or
                require temporary deferral.
              </li>
              <li>
                <b>Medical History:</b> Past or present medical conditions may
                affect eligibility.
              </li>
              <li>
                <b>Lifestyle Factors: </b>
                High-risk behaviors or recent procedures like tattoos may impact
                donation eligibility.
              </li>
            </ul>
          </div>
        </div>

        {/* 
          QUESTION 4
          ENDS 
          HERE */}

        {/* 
          QUESTION 5
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 5
                ? setExploreSectionContentActive(5)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              Who can't donate?
            </p>
            <div
              className={
                ExploreSectionContentActive === 5
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 5
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            <ul>
              <li>
                <b>Age:</b> Typically individuals under 17 years old (or 16
                without parental consent).
              </li>
              <li>
                <b>Weight: </b> Not meeting minimum weight requirements, usually
                around 50 kgs.
              </li>
              <li>
                <b>Height:</b> Not typically a specific factor for
                disqualification.
              </li>
              <li>
                <b>Health:</b> Recent travel to certain high-risk regions may
                disqualify donors.
              </li>
              <li>
                <b>Travel History:</b> Recent travel to certain regions may
                effect eligibility.
              </li>
              <li>
                <b>Medication:</b> Some medications can disqualify donors or
                require temporary deferral.
              </li>
              <li>
                <b>Medical History:</b> Past or present medical conditions such
                as bloodborne diseases may disqualify donors.
              </li>
              <li>
                <b>Lifestyle Factors: </b>
                High-risk behaviors like intravenous drug use or recent tattoos
                may prevent donation.
              </li>
            </ul>
          </div>
        </div>

        {/* 
          QUESTION 5
          ENDS 
          HERE */}

        {/* 
          QUESTION 6 
          STARTS 
          HERE */}

        <div className="explore-section-content-section">
          <div
            className="explore-section-content-header"
            onClick={() =>
              ExploreSectionContentActive !== 6
                ? setExploreSectionContentActive(6)
                : setExploreSectionContentActive(0)
            }
          >
            <p className="explore-section-content-header-heading">
              What is Blood Donation?
            </p>
            <div
              className={
                ExploreSectionContentActive === 6
                  ? 'explore-section-content-header-arrow down'
                  : 'explore-section-content-header-arrow'
              }
            >
              <IoIosArrowDown size={24} />
            </div>
          </div>
          <div
            className={
              ExploreSectionContentActive === 6
                ? 'explore-section-content-section-information open'
                : 'explore-section-content-section-information'
            }
          >
            Blood donation is a voluntary act where an individual gives blood to
            be used for medical purposes. It involves collecting blood through a
            needle from a donor's vein, typically in the arm. This blood is then
            processed and used for transfusions, medical treatments, or
            research.
          </div>
        </div>

        {/* 
          QUESTION 6
          ENDS 
          HERE */}


        
      </div>
    </div>
  );
}
